# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache:
  - packages: true

warnings_are_errors: true
r_check_args: "--as-cran"

matrix:
  include:
  - r: devel
  - r: release
    r_github_packages:
    - r-lib/covr
    - jimhester/lintr
    - r-lib/pkgdown
    after_success:
    - R CMD INSTALL $PKG_TARBALL
    - Rscript -e 'covr::codecov()'
    - Rscript -e 'lintr::lint_package()'
    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github()'
      skip_cleanup: true

notifications:
  email:
    on_success: always
    on_failure: always
