# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_all_nodes <- function(tree) {
    .Call(`_sdcHierarchies_rcpp_all_nodes`, tree)
}

rcpp_rootnode <- function(tree) {
    .Call(`_sdcHierarchies_rcpp_rootnode`, tree)
}

rcpp_is_rootnode <- function(tree, leaf) {
    .Call(`_sdcHierarchies_rcpp_is_rootnode`, tree, leaf)
}

rcpp_children <- function(tree, leaf) {
    .Call(`_sdcHierarchies_rcpp_children`, tree, leaf)
}

rcpp_parent <- function(tree, leaf) {
    .Call(`_sdcHierarchies_rcpp_parent`, tree, leaf)
}

rcpp_siblings <- function(tree, leaf) {
    .Call(`_sdcHierarchies_rcpp_siblings`, tree, leaf)
}

rcpp_exists <- function(tree, leaf) {
    .Call(`_sdcHierarchies_rcpp_exists`, tree, leaf)
}

rcpp_bogus_codes <- function(tree) {
    .Call(`_sdcHierarchies_rcpp_bogus_codes`, tree)
}

rcpp_replace_with_bogusparent <- function(bogus_info, leaf) {
    .Call(`_sdcHierarchies_rcpp_replace_with_bogusparent`, bogus_info, leaf)
}

rcpp_leafinfo <- function(tree, leaf) {
    .Call(`_sdcHierarchies_rcpp_leafinfo`, tree, leaf)
}

rcpp_level <- function(tree, leaf) {
    .Call(`_sdcHierarchies_rcpp_level`, tree, leaf)
}

rcpp_levels <- function(tree) {
    .Call(`_sdcHierarchies_rcpp_levels`, tree)
}

rcpp_nr_levels <- function(tree) {
    .Call(`_sdcHierarchies_rcpp_nr_levels`, tree)
}

rcpp_path <- function(tree, leaf) {
    .Call(`_sdcHierarchies_rcpp_path`, tree, leaf)
}

rcpp_is_bogus <- function(tree, leaf) {
    .Call(`_sdcHierarchies_rcpp_is_bogus`, tree, leaf)
}

rcpp_all_leaves <- function(tree) {
    .Call(`_sdcHierarchies_rcpp_all_leaves`, tree)
}

rcpp_contains_hier <- function(tree, leaf, upper) {
    .Call(`_sdcHierarchies_rcpp_contains_hier`, tree, leaf, upper)
}

rcpp_contributing_leaves <- function(tree, leaf) {
    .Call(`_sdcHierarchies_rcpp_contributing_leaves`, tree, leaf)
}

rcpp_is_minimal_code <- function(tree) {
    .Call(`_sdcHierarchies_rcpp_is_minimal_code`, tree)
}

rcpp_minimal_codes <- function(tree) {
    .Call(`_sdcHierarchies_rcpp_minimal_codes`, tree)
}

rcpp_is_subtotal <- function(tree) {
    .Call(`_sdcHierarchies_rcpp_is_subtotal`, tree)
}

rcpp_subtotals <- function(tree) {
    .Call(`_sdcHierarchies_rcpp_subtotals`, tree)
}

rcpp_prune <- function(tree, leaf) {
    .Call(`_sdcHierarchies_rcpp_prune`, tree, leaf)
}

rcpp_info <- function(tree, leaf) {
    .Call(`_sdcHierarchies_rcpp_info`, tree, leaf)
}

